# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0151f85f10f018dd0a475cac1695137df12008f8ad7477c70135a006467c602bbca8acdd6db9db03c4f28165c70d85e501f9065dc6021912530b962237e07b6b

test:
  secret_key_base: 7c53f18dc5c0aed313be3c36fbc6e81c79457e8244d49c1e621e24a4b7c8c52bf19bbc16ad2682aee842b2fc9678d874ce342175b01062d34b9a7e3a95e6b802

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7c53f18dc5c0aed313be3c36fbc6e81c79457e8244d49c1e621e24a4b7c8c52bf19bbc16ad2682aee842b2fc9678d874ce342175b01062d34b9a7e3a95e6b802

